import React, { useMemo } from 'react'
import { VerticalTimeline, VerticalTimelineElement } from 'react-vertical-timeline-component';
import 'react-vertical-timeline-component/style.min.css';
import moment from 'moment'
import 'moment/locale/zh-cn'
import { useTheme } from '@material-ui/core';
import * as _ from 'lodash'

moment.locale("zh-cn")

// Generated by https://quicktype.io

export interface entry {
    ccfCategory: string;
    confAbbrev: string;
    confName: string;
    hoster: string;
    dblp: string;
    range: Array<null | string>;
    location: string;
    ddl: null | string;
    type: string;
    level: string;
}



export default function Timeline(props: { data: entry[] }) {
    const theme = useTheme()
    const data = useMemo(() => (
        _.sortBy(props.data, (a) => moment(a.ddl).set('year', 2020).unix())
    ), [props.data])

    return (
        <div>
            <VerticalTimeline>
                {
                    data.map(e => (
                        <VerticalTimelineElement
                            className="vertical-timeline-element--work"
                            contentStyle={{ background: theme.palette.background.paper, color: theme.palette.text.secondary }}
                            contentArrowStyle={{ borderRight: '7px solid  rgb(33, 150, 243)' }}
                            date={moment(e.ddl).locale('zh-cn').format('MMMM DD日')}
                            iconStyle={{ background: theme.palette.primary[600], color: '#fff' }}
                            key={e.dblp}
                        >
                            <h3 className="vertical-timeline-element-title">{e.confAbbrev}</h3>
                            <h4 className="vertical-timeline-element-subtitle">{e.location}</h4>
                            <p>
                                <a>
                                    {e.confName}
                                </a>
                                <span style={{ marginLeft: "1rem" }}><a href={e.dblp} target="_blank">Link</a></span>
                            </p>
                        </VerticalTimelineElement>
                    ))
                }
                <VerticalTimelineElement
                    iconStyle={{ background: 'rgb(16, 204, 82)', color: '#fff' }}
                    date={"Have fun doing research~"}
                />
            </VerticalTimeline>
        </div>
    )
}
