// Generated by https://quicktype.io


export interface  IQuery{
    allMarkdownRemark: AllMarkdownRemark;
}

export interface AllMarkdownRemark {
    edges: Edge[];
}

export interface Edge {
    node: Node;
}

export interface Node {
    id:               string;
    excerpt:          string;
    fields:           Fields;
    fileAbsolutePath: string;
    frontmatter:      Frontmatter;
}

export interface Fields {
    slug: string;
}

export interface Frontmatter {
    title:    string;
    codeName: string;
    date:     string;
    tags:     string[] | null;
}



module.exports= 