// Generated by https://quicktype.io


export interface IQuery {
    allMarkdownRemark: AllMarkdownRemark;
}

export interface AllMarkdownRemark {
    edges: Edge[];
    pageInfo: PageInfo
}
// Generated by https://quicktype.io

export interface PageInfo {
    currentPage: number;
    hasNextPage: boolean;
    hasPreviousPage: boolean;
    itemCount: number;
    pageCount: number;
    perPage: number;
}



export interface Edge {
    node: Node;
}

export interface Node {
    id: string;
    excerpt: string;
    fields: Fields;
    fileAbsolutePath: string;
    timeToRead: number;
    frontmatter: Frontmatter;
}

export interface Fields {
    slug: string;
}

export interface Frontmatter {
    title: string;
    codeName: string;
    date: string;
    tags: string[] | null;
}


